---
title: Pride and Prejudice for zombies
hero_image: images/banner.png
description: Create a zombie-friendly version of Jane Austen's novel to placate our
  new cadaverous overlords
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: green
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: literature
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2018-10-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Making it all about Zombies
- title: Multiple similar replacements
- title: Zombies everywhere.
- title: The zombies are on the case
- title: Zombies moan and groan
- title: Zombie Austen
- title: Adding functions
- title: Zombie language
- title: Rule 2
- title: Rule 3 and 4
- title: Putting the translator together
- title: Finding speech
- title: Finishing Off
  completion: internal
- title: 'Challenge: Taking it further'
